[package]
name = "rusty-rays"
version = "0.1.0"
edition = "2024"
authors = ["Cameron Lyons <cameron.lyons2@gmail.com>"]

[dependencies]
clap = { version = "4.5", features = ["derive"] }
image = "0.25"
rand = "0.9"
rayon = "1.11"
